# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
on:
  repository_dispatch: {}

jobs:
  run_greeter:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
